-- Migration 008: Create tenants table for multi-tenant foundation
--
-- Safe to run on any existing database. Uses CREATE TABLE IF NOT EXISTS
-- so re-running this migration has no effect if the table already exists.
-- No existing tables are altered.
--
-- id is a TEXT UUID generated by the application before insert.
-- plan and status are enforced in application code, not via CHECK constraints,
-- so new values can be added in future without requiring another migration.
--
-- Run once against your existing toolsmith.db:
--   sqlite3 data/toolsmith.db < migrations/008_create_tenants_table.sql

CREATE TABLE IF NOT EXISTS tenants (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    plan       TEXT NOT NULL DEFAULT 'free',
    status     TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
